<?php
// Routes — all methods are GET or POST for Hostinger Nginx compatibility
// DELETE/PUT are tunnelled via POST with _method field (handled in Router.php)

return [
    // Public routes
    ['GET',  '/',                          'HomeController@index'],
    ['GET',  '/shop',                        'HomeController@shop'],
    ['GET',  '/categories',                  'HomeController@categories'],
    ['GET',  '/shop/{category}',             'CategoryController@show'],
    ['GET',  '/product/{slug}',            'ProductController@show'],
    ['GET',  '/brand/{slug}',              'BrandController@show'],
    ['GET',  '/brands',                    'BrandController@index'],
    ['GET',  '/search',                    'SearchController@index'],
    ['GET',  '/deals',                     'CategoryController@deals'],
    ['GET',  '/about',                     'HomeController@about'],
    ['GET',  '/contact',                   'HomeController@contact'],
    ['POST', '/contact',                   'HomeController@contactSubmit'],
    ['GET',  '/faq',                       'HomeController@faq'],
    ['GET',  '/shipping-policy',           'HomeController@shippingPolicy'],
    ['GET',  '/returns-policy',            'HomeController@returnsPolicy'],
    ['GET',  '/privacy-policy',            'HomeController@privacyPolicy'],
    ['GET',  '/terms',                     'HomeController@terms'],

    // Age gate
    ['GET',  '/age-verify',                'AgeGateController@show'],
    ['POST', '/age-verify',                'AgeGateController@verify'],

    // Cart
    ['GET',  '/cart',                      'CartController@index'],
    ['POST', '/cart/add',                  'CartController@add'],
    ['POST', '/cart/update',               'CartController@update'],
    ['POST', '/cart/remove',               'CartController@remove'],

    // Checkout
    ['GET',  '/checkout',                  'CheckoutController@index'],
    ['POST', '/checkout/place-order',      'CheckoutController@placeOrder'],
    ['GET',  '/order/confirm/{id}',        'OrderController@confirm'],
    ['GET',  '/track/{order_number}',      'OrderController@track'],

    // Auth
    ['GET',  '/login',                     'AuthController@loginForm'],
    ['POST', '/login',                     'AuthController@login'],
    ['GET',  '/register',                  'AuthController@registerForm'],
    ['POST', '/register',                  'AuthController@register'],
    ['GET',  '/forgot-password',           'AuthController@forgotForm'],
    ['POST', '/forgot-password',           'AuthController@forgot'],
    ['GET',  '/reset-password/{token}',    'AuthController@resetForm'],
    ['POST', '/reset-password/{token}',    'AuthController@reset'],
    ['GET',  '/logout',                    'AuthController@logout'],
    ['GET',  '/verify-email/{token}',      'AuthController@verifyEmail'],
    ['GET',  '/otp/verify',                'AuthController@otpForm'],
    ['POST', '/otp/verify',                'AuthController@otpVerify'],
    ['POST', '/otp/resend',                'AuthController@otpResend'],

    // Payment callbacks
    ['GET',  '/payment/stripe/success',    'PaymentController@stripeSuccess'],
    ['GET',  '/payment/stripe/failed',     'PaymentController@stripeFailed'],
    ['GET',  '/payment/telr/success',      'PaymentController@telrSuccess'],
    ['GET',  '/payment/telr/failed',       'PaymentController@telrFailed'],
    ['GET',  '/payment/tabby/success',     'PaymentController@tabbySuccess'],
    ['GET',  '/payment/tabby/failed',      'PaymentController@tabbyFailed'],
    ['GET',  '/payment/tamara/success',    'PaymentController@tamaraSuccess'],
    ['GET',  '/payment/tamara/failed',     'PaymentController@tamaraFailed'],
    ['POST', '/payment/tamara/webhook',    'PaymentController@tamaraWebhook'],

    // Account (auth required)
    ['GET',  '/account',                   'AccountController@dashboard'],
    ['GET',  '/account/orders',            'AccountController@orders'],
    ['GET',  '/account/order/{id}',        'AccountController@orderDetail'],
    ['GET',  '/account/profile',           'AccountController@profileForm'],
    ['POST', '/account/profile',           'AccountController@profileUpdate'],
    ['GET',  '/account/addresses',         'AccountController@addresses'],
    ['POST', '/account/addresses',         'AccountController@addAddress'],
    ['POST', '/account/addresses/{id}',    'AccountController@updateAddress'],
    ['POST', '/account/addresses/{id}/delete', 'AccountController@deleteAddress'],
    ['GET',  '/account/wishlist',          'AccountController@wishlist'],
    ['GET',  '/account/rewards',           'AccountController@rewards'],
    ['GET',  '/account/change-password',   'AccountController@changePasswordForm'],
    ['POST', '/account/change-password',   'AccountController@changePassword'],

    // Admin
    ['GET',  '/admin',                     'AdminController@dashboard'],
    ['GET',  '/admin/products',            'AdminController@products'],
    ['GET',  '/admin/products/create',     'AdminController@productCreate'],
    ['POST', '/admin/products/create',     'AdminController@productStore'],
    ['GET',  '/admin/products/{id}/edit',  'AdminController@productEdit'],
    ['POST', '/admin/products/{id}/edit',  'AdminController@productUpdate'],
    ['POST', '/admin/products/{id}/delete','AdminController@productArchive'],
    ['POST', '/admin/products/{id}/restore','AdminController@productRestore'],
    ['POST', '/admin/products/{id}/destroy','AdminController@productDestroy'],
    ['GET',  '/admin/categories',          'AdminController@categories'],
    ['POST', '/admin/categories',          'AdminController@categoryStore'],
    ['POST', '/admin/categories/{id}',     'AdminController@categoryUpdate'],
    ['GET',  '/admin/brands',              'AdminController@brands'],
    ['POST', '/admin/brands',              'AdminController@brandStore'],
    ['GET',  '/admin/orders',              'AdminController@orders'],
    ['GET',  '/admin/orders/{id}',         'AdminController@orderDetail'],
    ['POST', '/admin/orders/{id}/status',  'AdminController@orderStatus'],
    ['GET',  '/admin/customers',           'AdminController@customers'],
    ['GET',  '/admin/customers/{id}',      'AdminController@customerDetail'],
    ['POST', '/admin/customers/{id}/ban',  'AdminController@customerBan'],
    ['GET',  '/admin/coupons',             'AdminController@coupons'],
    ['POST', '/admin/coupons',             'AdminController@couponStore'],
    ['POST', '/admin/coupons/{id}/delete', 'AdminController@couponDelete'],
    ['GET',  '/admin/banners',             'AdminController@banners'],
    ['POST', '/admin/banners',             'AdminController@bannerStore'],
    ['POST', '/admin/banners/{id}/delete', 'AdminController@bannerDelete'],
    ['GET',  '/admin/reviews',             'AdminController@reviews'],
    ['POST', '/admin/reviews/{id}/approve','AdminController@reviewApprove'],
    ['POST', '/admin/reviews/{id}/reject', 'AdminController@reviewReject'],
    ['GET',  '/admin/reports',             'ReportController@index'],
    ['GET',  '/admin/reports/export',      'ReportController@export'],
    ['GET',  '/admin/reports/invoice/{id}','ReportController@invoicePdf'],
    ['GET',  '/admin/settings',            'AdminController@settings'],
    ['POST', '/admin/settings',            'AdminController@settingsUpdate'],
    ['GET',  '/admin/delivery-zones',      'AdminController@deliveryZones'],
    ['POST', '/admin/delivery-zones',      'AdminController@deliveryZoneStore'],
    ['POST', '/admin/delivery-zones/{id}', 'AdminController@deliveryZoneUpdate'],
    ['POST', '/admin/delivery-zones/{id}/delete', 'AdminController@deliveryZoneDelete'],
    ['GET',  '/admin/flavours',            'AdminController@flavours'],
    ['POST', '/admin/flavours',            'AdminController@flavourStore'],
    ['POST', '/admin/flavours/{id}',       'AdminController@flavourUpdate'],
    ['POST', '/admin/flavours/{id}/delete','AdminController@flavourDelete'],
    ['POST', '/admin/banners/{id}/edit',   'AdminController@bannerUpdate'],
    ['POST', '/admin/brands/{id}/edit',    'AdminController@brandUpdate'],
    ['POST', '/admin/brands/{id}/delete',  'AdminController@brandDelete'],
    ['POST', '/admin/coupons/{id}/edit',   'AdminController@couponUpdate'],

    // API — all POST (no DELETE/PUT — Nginx blocks them on shared hosting)
    ['POST', '/api/cart/add',              'ApiController@cartAdd'],
    ['POST', '/api/cart/update',           'ApiController@cartUpdate'],
    ['POST', '/api/cart/remove',           'ApiController@cartRemove'],
    ['POST', '/api/cart/edit-item',        'ApiController@cartEditItem'],
    ['GET',  '/api/cart',                  'ApiController@cartGet'],
    ['POST', '/api/cart/coupon',           'ApiController@cartCoupon'],
    ['POST', '/api/cart/coupon/remove',    'ApiController@cartCouponRemove'],
    ['GET',  '/api/products/search',       'ApiController@productSearch'],
    ['GET',  '/api/products/{id}/variants',     'ApiController@productVariants'],
    ['GET',  '/api/products/{id}/flavours',     'ApiController@productFlavours'],
    ['GET',  '/api/products/{id}/variations',                        'ApiController@productVariations'],
    ['POST', '/api/products/{id}/variations',                        'ApiController@productVariationsSave'],
    ['POST', '/api/products/{id}/variations/{combinationId}/update', 'ApiController@productVariationCombinationUpdate'],
    ['POST', '/api/wishlist/toggle',       'ApiController@wishlistToggle'],
    ['GET',  '/api/wishlist',              'ApiController@wishlistGet'],
    ['POST', '/api/reviews',               'ApiController@reviewSubmit'],
    ['POST', '/api/reviews/{id}/helpful',  'ApiController@reviewHelpful'],
    ['GET',  '/api/delivery/estimate',     'ApiController@deliveryEstimate'],
    ['POST', '/api/coupon/validate',       'ApiController@couponValidate'],
    ['GET',  '/api/account/notifications', 'ApiController@notifications'],
    ['POST', '/api/account/notifications/read', 'ApiController@notificationsRead'],
    ['GET',  '/api/age-verify/status',     'ApiController@ageVerifyStatus'],
    ['POST', '/api/newsletter/subscribe',  'ApiController@newsletterSubscribe'],

    // Admin API — all POST (tunnelled DELETE/PUT via _method field)
    ['GET',  '/api/admin/dashboard/stats',       'ApiController@adminStats'],
    ['GET',  '/api/admin/orders',                'ApiController@adminOrders'],
    ['POST', '/api/admin/orders/{id}/status',    'ApiController@adminOrderStatus'],
    ['GET',  '/api/admin/products',              'ApiController@adminProducts'],
    ['POST', '/api/admin/products',              'ApiController@adminProductCreate'],
    ['POST', '/api/admin/products/{id}',         'ApiController@adminProductUpdate'],
    ['POST', '/api/admin/products/{id}/delete',  'ApiController@adminProductDelete'],
    ['POST', '/api/admin/products/{id}/destroy', 'ApiController@adminProductDestroy'],
    ['POST', '/api/admin/products/{id}/images',  'ApiController@adminProductImages'],
    ['POST', '/api/admin/products/images/{id}/delete', 'ApiController@adminProductImageDelete'],
    ['GET',  '/api/admin/customers',             'ApiController@adminCustomers'],
    ['POST', '/api/admin/customers/{id}/ban',    'ApiController@adminCustomerBan'],
    ['POST', '/api/admin/coupons',               'ApiController@adminCouponCreate'],
    ['POST', '/api/admin/banners/sort',          'ApiController@adminBannersSort'],
    ['GET',  '/api/admin/reports/sales',         'ApiController@adminReportsSales'],
    ['GET',  '/api/admin/inventory/low-stock',   'ApiController@adminLowStock'],
];
